### ISSUE TITLE
Library TODO

### ISSUE THREAD

**Issue by rcastle1** [badgerloop-software/podiv-altium#16]
Make a component symbol for the following:
- [x] [40-Position Right Angle D-sub](https://www.digikey.com/product-detail/en/te-connectivity-amp-connectors/6-5173277-2/A114311-ND/2203212`)
- [x] [Shrouded 0.1" Header](https://www.digikey.com/product-detail/en/on-shore-technology-inc/302-S201/ED10524-ND/2794235)
- [x] [Right angle DB-9 RCPT](https://www.digikey.com/product-detail/en/assmann-wsw-components/A-DF-09-A-KG-T2S/AE10921-ND/1241800)
- [x] [Right angle DB-9 PLUG](https://www.digikey.com/product-detail/en/assmann-wsw-components/A-DS-09-A-KG-T2S/AE10968-ND/1241804)
- [x] 0.1" Headers, 1x2, 2x2, 2x3...2x10

Make a component footprint for the following
- [x] 40-Position Right Angle D-sub
- [x] Shrouded 0.1" Header
- [x] Right Angle DB-9 RCPT
- [x] Right Angle DB-9 PLUG
- [x] 0.1" Headers, 1x2, 2x2, 2x3...2x10

**Comment by nickbeckwith** [comment]
Have the 40 position right angle d-sub almost ready. Might need help getting a 3d model and footprint for it though.

**Comment by vkottler** [comment]
What's that 40-Position D-sub going to be for @rcastle1

**Comment by vkottler** [comment]
@nickbeckwith @rcastle1 if there's no 3D model available through ultra-librarian or linked from the part on Digi-Key we might want to choose a different part

**Comment by nickbeckwith** [comment]
@vkottler @rcastle1 Okay, I can't find any models through either so I'll look around for another part if it's still necessary

**Comment by badgerbricker** [comment]
working on Right angle DB-9 RCPT making footprint
